In [54]:
import pandas as pd

In [55]:
df= pd.read_csv("Credit (1).csv")

In [56]:
df

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,unemployed,married,primary,1787,no,79.0,1,no
1,33.0,services,married,secondary,4789,yes,220.0,1,no
2,35.0,management,single,tertiary,1350,yes,185.0,1,no
3,30.0,management,married,tertiary,1476,yes,199.0,4,no
4,59.0,blue-collar,married,secondary,0,yes,226.0,1,no
...,...,...,...,...,...,...,...,...,...
4516,99.0,services,married,secondary,-333,yes,329.0,5,no
4517,57.0,self-employed,married,tertiary,-3313,yes,-153.0,1,no
4518,57.0,technician,married,secondary,295,no,151.0,11,no
4519,28.0,blue-collar,married,secondary,1137,no,129.0,4,no
4520,44.0,entrepreneur,single,tertiary,1136,yes,345.0,2,no

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4519 non-null   float64
 1   job        4515 non-null   object
 2   marital    4518 non-null   object
 3   education  4517 non-null   object
 4   balance    4521 non-null   int64
 5   housing    4518 non-null   object
 6   duration   4519 non-null   float64
 7   campaign   4521 non-null   int64
 8   approval   4521 non-null   object
dtypes: float64(2), int64(2), object(5)
memory usage: 318.0+ KB

In [58]:
# To check the shape of file

df.shape

(4521, 9)

In [59]:
df.dtypes

age          float64
job           object
marital       object
education     object
balance        int64
housing       object
duration     float64
campaign       int64
approval      object
dtype: object

In [60]:
# df.drop(['marital','education','campaign'],axis=1,inplace=True)

In [61]:
# df.to_csv('Credit_dropped.csv',index=False)

In [62]:
# Separating the data based on objects:
  # Data that include objects- char
  # Data that exclude objects- num

In [63]:
char =df.select_dtypes(include='object')

In [64]:
char

                job  marital  education housing approval
0        unemployed  married    primary      no       no
1          services  married  secondary     yes       no
2        management   single   tertiary     yes       no
3        management  married   tertiary     yes       no
4       blue-collar  married  secondary     yes       no
...             ...      ...        ...     ...      ...
4516       services  married  secondary     yes       no
4517  self-employed  married   tertiary     yes       no
4518     technician  married  secondary      no       no
4519    blue-collar  married  secondary      no       no
4520   entrepreneur   single   tertiary     yes       no

[4521 rows x 5 columns]

In [65]:
num =df.select_dtypes(exclude='object')

In [66]:
num

       age  balance  duration  campaign
0     30.0     1787      79.0         1
1     33.0     4789     220.0         1
2     35.0     1350     185.0         1
3     30.0     1476     199.0         4
4     59.0        0     226.0         1
...    ...      ...       ...       ...
4516  99.0     -333     329.0         5
4517  57.0    -3313    -153.0         1
4518  57.0      295     151.0        11
4519  28.0     1137     129.0         4
4520  44.0     1136     345.0         2

[4521 rows x 4 columns]

In [67]:
# Encoding the char objects:

In [68]:
char['job'].unique( )

array(['unemployed', 'services', 'management', 'blue-collar',
       'self-employed', 'technician', 'entrepreneur', 'admin.', 'student',
       'housemaid', 'retired', 'unknown', nan], dtype=object)

In [69]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder() 


char['job']=le.fit_transform(char['job'])

In [70]:
char['job'].unique( )

array([10,  7,  4,  1,  6,  9,  2,  0,  8,  3,  5, 11, 12])

In [71]:
char['marital'].unique( )

array(['married', 'single', 'divorced', nan], dtype=object)

In [72]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder() 


char['marital']=le.fit_transform(char['marital'])

In [73]:
char['marital'].unique( )

array([1, 2, 0, 3])

In [74]:
char['education'].unique( )

array(['primary', 'secondary', 'tertiary', 'unknown', nan], dtype=object)

In [75]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder() 


char['education']=le.fit_transform(char['education'])

In [76]:
char['education'].unique( )

array([0, 1, 2, 3, 4])

In [77]:
char['housing'].unique( )

array(['no', 'yes', nan], dtype=object)

In [78]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder() 


char['housing']=le.fit_transform(char['housing'])

In [79]:
char['housing'].unique( )

array([0, 1, 2])

In [80]:
char['approval'].unique( )

array(['no', 'yes'], dtype=object)

In [81]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder() 


char['approval']=le.fit_transform(char['approval'])

In [82]:
char['approval'].unique( )

array([0, 1])

In [83]:
char

      job  marital  education  housing  approval
0      10        1          0        0         0
1       7        1          1        1         0
2       4        2          2        1         0
3       4        1          2        1         0
4       1        1          1        1         0
...   ...      ...        ...      ...       ...
4516    7        1          1        1         0
4517    6        1          2        1         0
4518    9        1          1        0         0
4519    1        1          1        0         0
4520    2        2          2        1         0

[4521 rows x 5 columns]

In [84]:
# Concatinating/ combining the num objects with encoded char objects:

clean_data=pd.concat([char,num],axis=1)

In [85]:
# Saving the cleaned data in a separate csv file to use further

clean_data.to_csv('Credit_cleaned.csv',index=False)

In [106]:
# Further cleaning of dataset:-

In [86]:
import pandas as pd

In [87]:
df= pd.read_csv("Credit_cleaned.csv")

In [88]:
df

,job,marital,education,housing,approval,age,balance,duration,campaign
0,10,1,0,0,0,30.0,1787,79.0,1
1,7,1,1,1,0,33.0,4789,220.0,1
2,4,2,2,1,0,35.0,1350,185.0,1
3,4,1,2,1,0,30.0,1476,199.0,4
4,1,1,1,1,0,59.0,0,226.0,1
...,...,...,...,...,...,...,...,...,...
4516,7,1,1,1,0,99.0,-333,329.0,5
4517,6,1,2,1,0,57.0,-3313,-153.0,1
4518,9,1,1,0,0,57.0,295,151.0,11
4519,1,1,1,0,0,28.0,1137,129.0,4
4520,2,2,2,1,0,44.0,1136,345.0,2

In [89]:
df.dropna(inplace=True)

x= df.drop('approval',axis=1)
y= df[['approval']]

In [90]:
x

      job  marital  education  housing   age  balance  duration  campaign
0      10        1          0        0  30.0     1787      79.0         1
1       7        1          1        1  33.0     4789     220.0         1
2       4        2          2        1  35.0     1350     185.0         1
3       4        1          2        1  30.0     1476     199.0         4
4       1        1          1        1  59.0        0     226.0         1
...   ...      ...        ...      ...   ...      ...       ...       ...
4516    7        1          1        1  99.0     -333     329.0         5
4517    6        1          2        1  57.0    -3313    -153.0         1
4518    9        1          1        0  57.0      295     151.0        11
4519    1        1          1        0  28.0     1137     129.0         4
4520    2        2          2        1  44.0     1136     345.0         2

[4517 rows x 8 columns]

In [91]:
y

      approval
0            0
1            0
2            0
3            0
4            0
...        ...
4516         0
4517         0
4518         0
4519         0
4520         0

[4517 rows x 1 columns]

In [92]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [93]:
x_train

      job  marital  education  housing   age  balance  duration  campaign
4062    4        2          1        1  43.0      109      64.0         3
804     4        1          2        1  40.0    -1212    1259.0         2
2319    4        1          1        0  44.0     -665     342.0         3
1035    0        1          1        1  38.0     1852     298.0         2
4106    9        2          1        1  33.0      647     124.0         1
...   ...      ...        ...      ...   ...      ...       ...       ...
4428    1        1          3        1  48.0      439     212.0         1
467     4        1          2        1  39.0     -606     142.0         1
3093    2        1          2        0  53.0       71      86.0         1
3773    9        1          1        0  34.0       47     132.0         6
861     4        1          2        0  48.0      866     146.0         2

[3613 rows x 8 columns]

In [94]:
y_train

      approval
4062         0
804          0
2319         0
1035         0
4106         0
...        ...
4428         0
467          0
3093         0
3773         0
861          0

[3613 rows x 1 columns]

In [95]:
x_test

      job  marital  education  housing   age  balance  duration  campaign
1566    2        1          0        1  45.0     2418     120.0         1
1420    9        2          2        1  29.0      452      59.0         1
4004    9        2          1        0  34.0      179     294.0         3
1075   10        1          2        1  26.0      454      28.0        18
3236    1        1          0        1  43.0     2519     257.0         2
...   ...      ...        ...      ...   ...      ...       ...       ...
2923    0        1          1        1  39.0      260     146.0         1
2046    7        2          1        1  21.0     1903     107.0         2
326    10        1          1        0  51.0     1760     162.0         1
3251    1        1          1        0  60.0     1801     167.0         1
2919    4        1          2        0  44.0     7635     719.0         5

[904 rows x 8 columns]

In [96]:
y_test

      approval
1566         0
1420         0
4004         0
1075         0
3236         0
...        ...
2923         0
2046         0
326          0
3251         0
2919         0

[904 rows x 1 columns]

In [132]:
# In this case, the chances of credit or loan is either yes or no... which means that the result is classified into 2 . 
# So here the case is for "Classification", not regression, hence linear regression cannot be used.
# Algorithms like SVM,KNN,Decision Tree can be used

## Algorithms to be applied

* Decision Tree
* SVM
* KNN

### Decision Tree

In [1]:
import pandas as pd
from sklearn.metrics import classification_report,precision_score,recall_score,f1_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("Credit_cleaned.csv")

In [3]:
df

,job,marital,education,housing,approval,age,balance,duration,campaign
0,10,1,0,0,0,30.0,1787,79.0,1
1,7,1,1,1,0,33.0,4789,220.0,1
2,4,2,2,1,0,35.0,1350,185.0,1
3,4,1,2,1,0,30.0,1476,199.0,4
4,1,1,1,1,0,59.0,0,226.0,1
...,...,...,...,...,...,...,...,...,...
4516,7,1,1,1,0,99.0,-333,329.0,5
4517,6,1,2,1,0,57.0,-3313,-153.0,1
4518,9,1,1,0,0,57.0,295,151.0,11
4519,1,1,1,0,0,28.0,1137,129.0,4
4520,2,2,2,1,0,44.0,1136,345.0,2

In [4]:
x= df.drop('approval',axis=1)
y= df[['approval']]

In [5]:
x

      job  marital  education  housing   age  balance  duration  campaign
0      10        1          0        0  30.0     1787      79.0         1
1       7        1          1        1  33.0     4789     220.0         1
2       4        2          2        1  35.0     1350     185.0         1
3       4        1          2        1  30.0     1476     199.0         4
4       1        1          1        1  59.0        0     226.0         1
...   ...      ...        ...      ...   ...      ...       ...       ...
4516    7        1          1        1  99.0     -333     329.0         5
4517    6        1          2        1  57.0    -3313    -153.0         1
4518    9        1          1        0  57.0      295     151.0        11
4519    1        1          1        0  28.0     1137     129.0         4
4520    2        2          2        1  44.0     1136     345.0         2

[4521 rows x 8 columns]

In [6]:
y

      approval
0            0
1            0
2            0
3            0
4            0
...        ...
4516         0
4517         0
4518         0
4519         0
4520         0

[4521 rows x 1 columns]

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [8]:
# making an object 

dt= DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [9]:
dt.score(x_test,y_test)

0.8408839779005525

In [10]:
dt.score(x_train,y_train)

1.0

In [11]:
pred = dt.predict(x_test)

In [13]:
pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [14]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.92      0.90      0.91       813
           1       0.26      0.30      0.28        92

    accuracy                           0.84       905
   macro avg       0.59      0.60      0.60       905
weighted avg       0.85      0.84      0.85       905

In [15]:
print(precision_score(y_test,pred))
print(recall_score(y_test,pred))
print(f1_score(y_test,pred))

0.25925925925925924
0.30434782608695654
0.28

In [16]:
print(confusion_matrix(y_test,pred))

[[733  80]
 [ 64  28]]

### SVM

In [ ]:
# from sklearn.ensemble import

In [114]:
df.dropna(inplace=True)

In [115]:
x= clean_data.drop('approval',axis=1)
y= clean_data[['approval']]

In [116]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [117]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_train,y_train)

ValueError: Input X contains NaN.
SVC does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [130]:
svr.score(x_test,y_test)

0.942965054098931

In [ ]:
svr.score(x_train,y_train)

## KNN (k- Nearest) Neighbours Algorithm

In [119]:
from sklearn.datasets import load_iris
x,y = load_iris(return_X_y=True)

In [120]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [121]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [122]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [123]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [124]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [125]:
knn.score(x_test,y_test)

0.9666666666666667

In [126]:
knn.score(x_train,y_train)

0.9583333333333334

In [127]:
knn.predict(x_test)

array([2, 1, 1, 0, 0, 2, 1, 1, 1, 2, 1, 0, 2, 0, 0, 0, 2, 2, 1, 1, 2, 2,
       1, 1, 0, 0, 2, 2, 0, 2])

In [128]:
y_test

array([2, 1, 1, 0, 0, 2, 2, 1, 1, 2, 1, 0, 2, 0, 0, 0, 2, 2, 1, 1, 2, 2,
       1, 1, 0, 0, 2, 2, 0, 2])